version: '3'

services:

  multiphp:
    image: leymannx/apache-multiphp
    restart: always
    ports:
      - 8856:8856
      - 8871:8871
    depends_on:
      - mariadb
    volumes:
      - ./www:/var/www:consistent
      - ./conf.d/php56.ini:/etc/php/5.6/fpm/conf.d/php56.ini:delegated
      - ./conf.d/php71.ini:/etc/php/7.1/fpm/conf.d/php71.ini:delegated
    working_dir: /var/www

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./databases:/var/lib/mysql:delegated
      - ./conf.d/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
    # Enable database 4 byte UTF-8 support.
    # command: mysqld --user=root --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
